### PR TITLE
RFE: add test for audit multicast join and part

### PR DESCRIPTION
**Pull request by rgbriggs**
Please see github audit kernel issue
	https://github.com/linux-audit/audit-kernel/issues/28

Signed-off-by: Richard Guy Briggs <rgb@redhat.com>

### CODE REVIEW

**Comment by rgbriggs** [comment]
the failed travis-ci test is due to ghak64 - saddr_fam

**Comment by The-Mule** [comment]
Richard, do you plan to update this to the version you have without perl package dependency?

**Comment by rgbriggs** [comment]
On 2020-05-25 12:17, Ondrej Moris wrote:
> Richard, do you plan to update this to the version you have without perl package dependency?

I haven't decided.  I like the clarity and simplicity of the dependancy, but portability of the open coding.

**Comment by The-Mule** [comment]
We would have to disable test on RHEL since perl-Socket-Netlink is not even in EPEL. On the other hand, the test runs on Fedora so I guess the risk of introducing regression in RHEL is very low. However, if you decide to keep perl-Socket-Netlink you will have to update tests/Makefile to filter-out new test on RHEL.

**Comment by rgbriggs** [comment]
@pcmoore Would you consider taking this branch instead?  The commented-out code provides a method to verify that the pack operation was correct.
https://github.com/rgbriggs/audit-testsuite/compare/ghak28-mcast-part-join.nolib

**Comment by pcmoore** [comment]
> Would you consider taking this branch instead?

In order to simplify things @rgbriggs, update this PR (or close and replace it with another, your choice) with what you would like me to review.  One PR with comments on multiple submissions is awkward.

**Comment by rgbriggs** [comment]
See https://github.com/linux-audit/audit-testsuite/pull/99

**Comment by rgbriggs** [comment]
On 2020-12-23 13:32, Paul Moore wrote:
> > Would you consider taking this branch instead?
> 
> In order to simplify things @rgbriggs, update this PR (or close and replace it with another, your choice) with what you would like me to review.  One PR with comments on multiple submissions is awkward.

Ok, closed this one and openned a new PR.

**Pull request closed without merging**
