### PR TITLE
RFE: add initial io_uring tests

### PR DESCRIPTION
**Pull request by pcmoore**
This is rather simple test using a basic set of io_uring operations
to open a file, write a string to it, read the string back out, and
then close the file.  The test verifies that the io_uring related
records are captured and marked with a given key value and that the
uring operation values are present.

Signed-off-by: Paul Moore <paul@paul-moore.com>

### CODE REVIEW

**Comment by pcmoore** [comment]
Test run output:
```
Running as   user    root
        with context unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023
        on   system  Fedora

backlog_wait_time_actual_reset/test .. ok   
exec_execve/test ..................... ok   
exec_name/test ....................... ok     
file_create/test ..................... ok   
file_delete/test ..................... ok   
file_rename/test ..................... ok   
filter_exclude/test .................. ok     
filter_saddr_fam/test ................ ok   
filter_sessionid/test ................ ok   
login_tty/test ....................... ok   
lost_reset/test ...................... ok   
netfilter_pkt/test ................... ok     
signal/test .......................... ok   
syscalls_file/test ................... ok   
syscall_module/test .................. ok   
syscall_socketcall/test .............. ok   
time_change/test ..................... ok     
user_msg/test ........................ ok   
fanotify/test ........................ ok   
bpf/test ............................. ok   
io_uring/test ........................ ok   
All tests successful.
Files=21, Tests=218, 48 wallclock secs ( 0.09 usr  0.03 sys + 17.69 cusr  1.99 csys = 19.80 CPU)
Result: PASS
```

**Comment by The-Mule** [comment]
Thanks Paul, all look good to me (r+).

**Comment by pcmoore** [comment]
Thanks for the review @The-Mule, can I add your `Reviewed-by:` tag?  I'm guessing that is what the "(r+)" means, but I don't want to assume too much :)

**Review by The-Mule — APPROVED** [review]

**Comment by pcmoore** [comment]
Merged via 033b3763f905198923526b9d32603c4ca821539c, thanks!

**Pull request closed without merging**
