### PR TITLE
RFE: add the bpf tests

### PR DESCRIPTION
**Pull request by olsajiri**
Adding test for bpf audit notification.

Kernel changes are on the way to upstream:
  https://lore.kernel.org/netdev/20191206214934.11319-1-jolsa@kernel.org/

audit-userspace changes are in here:
https://github.com/linux-audit/audit-userspace/pull/104

### CODE REVIEW

**Comment by pcmoore** [comment]
Thanks @olsajiri, unfortunately it looks like the Travis build identified some style problems with the PR, can you fix those?

**Comment by olsajiri** [comment]
@pcmoore , that check-syntax stuff forced me to 'fix' bpf.c so it looks mighty ugly now  ;-)

also I had to change some other source that did not come from me

**Comment by olsajiri** [comment]
@pcmoore ping, thanks

**Comment by pcmoore** [comment]
Hi @olsajiri, generally I don't merge new tests until the kernel code has reached Linus' tree or the audit/next branch.

**Comment by olsajiri** [comment]
@pcmoore ok, so I assume you're ok with the change..?

**Comment by pcmoore** [comment]
Sorry, I haven't had a chance to look at it beyond the initial comments yet.

**Comment by pcmoore** [comment]
Merged via e7a70dc7d6a4a831bdba9cb4db25c08786f6ac73, thanks @olsajiri!

**Pull request closed without merging**
