### PR TITLE
RFE: GHAK #100 missing mount hang

### PR DESCRIPTION
**Pull request by rgbriggs**

### CODE REVIEW

**Comment by pcmoore** [comment]
My apologies, I reviewed this a while ago but didn't use the GH tool properly so I don't believe the comments were visible until just now.

**Comment by rgbriggs** [comment]
On 2018-12-12 09:43, Paul Moore wrote:
> +	syscall_umount2 \
> 
> This isn't really a functionality test is it?  It seems more like a bug specific test, yes?

I guess I'm slowly coming around to understand the distinction between the two, but still don't understand how a bug-specific test is different from a regression test or why that matters.

> > @@ -0,0 +1,14 @@
> +	git clone git://github.com/libfuse/libfuse.git -b fuse_2_9_bugfix
> 
> I'm not a fan of requiring network access to run tests.  If this is something we want to merge (and I'm not sure it is, see comment in tests/Makefile) then we should keep a copy local to the test suite (ugh, very not desirable) if we can't rely on distro packages.

I thought this was pretty ugly too.  I did a bit of back and forth with the fuse guys to come up with a better way that was based on stock binary packages.  This test source code is part of the code base, but not compiled in any distro, so only available as source (maybe in the source rpms), depending on its package library to build.  There are certainly other ways such as to use NFS and temp firewall its server, but that's worse.  As you point out, snapshotting that source file and using the package devel lib to build it would avoid network need, but is still ugly.

**Comment by pcmoore** [comment]
> I guess I'm slowly coming around to understand the distinction between the two, but still don't understand how a bug-specific test is different from a regression test or why that matters.

I really want to keep the audit-testsuite relatively small and easy to run; this of course is a balancing act as coverage is obviously *very* important for a test suite.  While I'm not going to disagree with test suites that proclaim "every bug gets a test!", I feel that adds unnecessary weight (and run time) to the test suite which detracts from its usefulness in a development setting.

If it helps understand my motivation, the audit-testsuite was created because the Common Criteria focused audit-test test suite was far too cumbersome to use on a regular basis for development.  The audit-test effort was (sadly I believe it has been abandoned) a great test suite, but in some ways it was too good - too comprehensive - for its own good.

**Comment by rgbriggs** [comment]
On 2018-12-13 15:33, Paul Moore wrote:
> > I guess I'm slowly coming around to understand the distinction between the two, but still don't understand how a bug-specific test is different from a regression test or why that matters.
> 
> I really want to keep the audit-testsuite relatively small and easy to run; this of course is a balancing act as coverage is obviously *very* important for a test suite.  While I'm not going to disagree with test suites that proclaim "every bug gets a test!", I feel that adds unnecessary weight (and run time) to the test suite which detracts from its usefulness in a development setting.

Fair enough.  It was never clear to me that this was to be a relatively quick test.  Where do you suggest putting bug tests?  We've added a manual section to audit-testsuite.  Does it make sense to add a bugs section, or short vs long test list?

**Comment by pcmoore** [comment]
> Where do you suggest putting bug tests?  We've added a manual section to audit-testsuite.  Does it make sense to add a bugs section, or short vs long test list?

The manual tests area is another tricky area, especially with the inclusion of Jan's stress test.  I think the manual tests area is going to be one of those case-by-case situations.  The module path filter is pretty clearly there to test functionality, and while the stress test is less clear, I believe it still exercises the functionality to verify proper operation and isn't a bug specific test.

However, to get back to your question about bug specific tests - I don't have a good suggestion for you at this point in time.  Perhaps this is something a distribution could drive as part of some CI effort? ;)

**Comment by rgbriggs** [comment]
On 2018-12-14 20:20, Paul Moore wrote:
> > Where do you suggest putting bug tests?  We've added a manual section to audit-testsuite.  Does it make sense to add a bugs section, or short vs long test list?
> 
> The manual tests area is another tricky area, especially with the inclusion of Jan's stress test.  I think the manual tests area is going to be one of those case-by-case situations.  The module path filter is pretty clearly there to test functionality, and while the stress test is less clear, I believe it still exercises the functionality to verify proper operation and isn't a bug specific test.
> 
> However, to get back to your question about bug specific tests - I don't have a good suggestion for you at this point in time.  Perhaps this is something a distribution could drive as part of some CI effort? ;)

Oh, having it in a distro CI test is the next obvious place for it, but this isn't a distro-specific bug, so I think it makes more sense to be upstream somewhere.  At least the test didn't just stop the entire suite if it failed, so wasn't on the destructive side of the manual tests...

**Comment by rgbriggs** [comment]
On 2018-12-14 21:27, Steve Grubb wrote:
> +  system("auditctl -A exit,always -S umount2 -F key=$key >& /dev/null");
> 
> This needs a -F arch=b64 added.

Nice catch.  Better yet: "-F arch=b$ENV{MODE}"

**Comment by pcmoore** [comment]
> Oh, having it in a distro CI test is the next obvious place for it, but this isn't a distro-specific bug, so I think it makes more sense to be upstream somewhere.

I said a distribution could drive it as part of a CI effort, I never said it had to be a distro-specific CI test.  That's an important distinction ;)

/me looks at @The-Mule as a possible collaborator on an effort like this.

My thinking is that if you are going to start collecting tests for each and every bug encountered (once again, not saying that is a bad goal, it is just out-of-scope for what I would like to accomplish with the audit-testsuite), the test run is going to grow to be very long over time ... assuming the test suite gains enough traction to become useful.  Long running tests like that are only going to get run on a regular basis if someone sets it up as part of an automated infrastructure, look at the many test bots that are running on the public mailing lists.

**Comment by rgbriggs** [comment]
On 2018-12-14 14:05, Richard Guy Briggs wrote:
> On 2018-12-14 21:27, Steve Grubb wrote:
> > +  system("auditctl -A exit,always -S umount2 -F key=$key >& /dev/null");
> > 
> > This needs a -F arch=b64 added.
> 
> Nice catch.  Better yet: "-F arch=b$ENV{MODE}"

'scuse the noise, but while we're at it, these could use updating:

tests/filter_sessionid/test:"auditctl -a always,exit -F arch=b64 -F path=/tmp/$key -F sessionid=$sessionid -k $key"
tests/syscall_module/test:"auditctl -a always,exit -F arch=b64 -S init_module -S finit_module -k $key-load"
tests/syscall_module/test:system("auditctl -a always,exit -F arch=b64 -S delete_module -k $key-unload");
tests_manual/syscall_module_path_filter/setup:echo "-a always,exit -F arch=b64 -S init_module -S finit_module -k ghak8-mod-load" > /etc/audit/rules.d/tests_manual-syscall_module_path_filter.rules

**Comment by pcmoore** [comment]
This still looks like a test for a specific bug and not a regression test so I'm going to go ahead and close this out.  @rgbriggs if you've got objections (beyond what has been mentioned above), let me know and we can reopen this issue/PR if needed.

**Pull request closed without merging**
