### PR TITLE
RFE: tests: add test for contid

### PR DESCRIPTION
**Pull request by rgbriggs**
See: https://github.com/linux-audit/audit-testsuite/issues/64

Signed-off-by: Richard Guy Briggs <rgb@redhat.com>

### CODE REVIEW

**Comment by pcmoore** [comment]
I'm guessing you didn't mean to close this @rgbriggs?

**Comment by rgbriggs** [comment]
On 2019-12-31 09:30, Paul Moore wrote:
> I'm guessing you didn't mean to close this @rgbriggs?

I didn't close it intentionally.  It must have been a by-product of a forced push.

**Comment by pcmoore** [comment]
You should probably reopen the issue then ;)

**Comment by rgbriggs** [comment]
On 2020-01-01 10:23, Paul Moore wrote:
> You should probably reopen the issue then ;) 

I would if I could, or understood how, but that reopen button is not active.

**Comment by pcmoore** [comment]
FWIW, the reopen button isn't available to me either, but I assumed that was due to you creating the PR (owner controlled?).

Anyway, it looks like this has moved to #91?

**Comment by rgbriggs** [comment]
On 2020-01-02 08:31, Paul Moore wrote:
> Anyway, it looks like this has moved to #91?

Yes, replaced by #91

**Pull request closed without merging**
