### PR TITLE
BUG: tests/user_msg: update for latest even format

### PR DESCRIPTION
**Pull request by The-Mule**
Recently, AUDIT_USER message updated its format, see [1].

[1] https://github.com/linux-audit/audit-userspace/commit/93c13545e3e96e97b8f0e52637662a3f9076cf27

### CODE REVIEW

**Comment by The-Mule** [comment]
Travis issue is caused by different test (lost_reset).

**Comment by rgbriggs** [comment]
On 2019-12-03 04:54, Ondrej Moris wrote:
> Travis issue is caused by different test (lost_reset).

The travis test is a nuisance since its output seems to change.  Whether
this is with travis updates or with other content added in the middle of
a source file affecting following lines is unclear to me.  I tried
setting travis up locally and failed to find and assemble the bits to do
it.

**Comment by pcmoore** [comment]
> Travis issue is caused by different test (lost_reset).

You can always submit a patch to fix those issues too ;)

Regardless, the perltidy formatting issue should now be fixed in d907608ee31d4d7fd969736a4d291c968fef53c8, I'll see if I can get Travis to re-test this PR.

**Comment by pcmoore** [comment]
> The travis test is a nuisance since its output seems to change. Whether this is with travis updates or with other content added in the middle of a source file affecting following lines is unclear to me. I tried setting travis up locally and failed to find and assemble the bits to do it.

Suggestions (other than turning off CI tests) are welcome.

**Comment by pcmoore** [comment]
@The-Mule does this work for both the old and new userspace tools?

**Comment by The-Mule** [comment]
Good point, Paul. Actually, no. Let me fix it.

**Comment by The-Mule** [comment]
Test now work with both old and new version of auditd.

**Comment by pcmoore** [comment]
Thanks @The-Mule, can I add your sign-off to the patch?
```
Signed-off-by: Ondrej Moris <omoris@redhat.com>
```

**Comment by The-Mule** [comment]
Absolutely, apologies for not adding it.

**Comment by pcmoore** [comment]
Thanks!  Merged via 33a94af2bd2a619d531ac632817c266f06a29b5f.

**Pull request closed without merging**
