### PR TITLE
RFE: fix SELinux parsing in the filter_exclude test

### PR DESCRIPTION
**Pull request by rgbriggs**

### CODE REVIEW

**Comment by pcmoore** [comment]
Okay, looking at these patches there appears to be a great deal of confusion regarding the format of SELinux labels; let me try to explain things a bit.

The SELinux label format consists of four fields, delimited by colons (":").  The format looks like the following:

    <USER>:<ROLE>:<TYPE>:<MLS>

The USER, ROLE, and TYPE fields can effectively be treated as simple alphanumeric strings with no sub-fields.  Unfortunately, the same can not be said of the MLS field.

The MLS field consists of a low and a high range, with each end of the range consisting of a sensitivity level and a category bitmap.  The two ends of the range are separated by a dash ("-") and the sensitivity level is separated from the category bitmap by a colon (":").  If the low and the high end of the range are the same, the high end may be omitted.  If the category bitmap is empty, it may be omitted.  The category bitmaps can further make use of a combination of commas (",") for listing sparse categories and periods (".") for listing an inclusive group of categories; for simplicity we'll ignore those here, but know these delimiters could/do exist in the category bitmap strings.  With all that in mind, we could write the SELinux label format as such:

    <USER>:<ROLE>:<TYPE>:<LVL(LOW)>[:<CAT(LOW)>][-<LVL(HIGH)>[:<CAT(HIGH)>]]

Some quick examples to help demonstrate the optional MLS fields.

First, a valid label with all MLS sub-fields visible:

    user_u:role_r:type_t:s0:c1-s2:c3

Now a simplified example with the same low and high range:

    user_u:role_r:type_t:s0:c1-s0:c1

... which would always be written in the simplified format as shown below (you don't list both ranges when they are identical):

    user_u:role_r:type_t:s0:c1

Now a label with an empty category bitmap in the low end of the range:

    user_u:role_r:type_t:s0-s1:c2

Finally a label with identical low and high ranges, and empty category bitmaps:

    user_u:role_r:type_t:s0

Hopefully this helps you make more sense of the SELinux label format.

**Comment by rgbriggs** [comment]
On 2018-12-12 09:25, Paul Moore wrote:
> I haven't seen any response to the info above, where are we on this?

It is still on my back burner to digest and address by coming up with a more correct parser to separate the parts.  Your explanation appeared to be very thorough , making it appear to me that it would be much more difficult to parse than originally anticipated.

> I guess an equally, if not more important question: what problem does this PR attempt to solve, or what new feature does it add?  Having that info stated clearly in the commit descriptions would help.

The original goal was to be able to set the selinux subj_sen and subj_clr filters using auditctl in the filter_exclude test and be able to parse and isolate them when checking the resulting records.

**Comment by pcmoore** [comment]
I just merged PR #96 which should resolve this so I'm going to close out this PR, thanks.

**Comment by rgbriggs** [comment]
I was hoping to modify this patch rebased on much more elegant solution that is https://github.com/linux-audit/audit-testsuite/pull/96 to add the extra bits once ghat96 was upstreamed, since there is still some value to this patch as noted in ghat96.  (I don't have perms to reopen, I guess I'll just do another pr...)

**Pull request closed without merging**
