### PR TITLE
RFE: test multicast join and part events without the perl socket netlink library dependancy

### PR DESCRIPTION
**Pull request by rgbriggs**
I'd prefer to keep both patches rather than squash them down and delete the commented out code, to show how the open code was derived and how to test/fix it in the future if it breaks.

### CODE REVIEW

**Comment by pcmoore** [comment]
Can we get a better name for this PR? :)

**Comment by rgbriggs** [comment]
On 2021-02-02 07:54, Paul Moore wrote:
> Can we get a better name for this PR? :)

Better?

**Comment by pcmoore** [comment]
Yes, thanks.

**Comment by pcmoore** [comment]
Looking at the two patches, I think I kinda prefer just leaving it at the first patch and ignoring/dropping the second - any objection @rgbriggs?

**Comment by rgbriggs** [comment]
On 2024-08-28 12:53, Paul Moore wrote:
> Looking at the two patches, I think I kinda prefer just leaving it at the first patch and ignoring/dropping the second - any objection @rgbriggs?

It was open coded due to lack of library support on all platforms tested.  I forgotten the details.

**Comment by pcmoore** [comment]
Merged the first patch, the library version, via 343a14664c74273139bf01b0f62b3b0e9638ff1c and left it at that for now, if needed we can revisit this to open code the library functions.  It is worth noting that I had to merge a fix, 8e13f9c4aae699a0796709e38018949fd4b1f65f, to get this test to pass on a current Rawhide system.

**Comment by rgbriggs** [comment]
On 2024-09-05 10:02, Paul Moore wrote:
> Merged the first patch, the library version, via 343a14664c74273139bf01b0f62b3b0e9638ff1c and left it at that for now, if needed we can revisit this to open code the library functions.  It is worth noting that I had to merge a fix, 8e13f9c4aae699a0796709e38018949fd4b1f65f, to get this test to pass on a current Rawhide system.

Thanks for the merge and the fixup.  I'll see if the upstream update works on all I need to test.

**Pull request closed without merging**
