### PR TITLE
RFE: execve/BPRM_FCAPS manual test

### PR DESCRIPTION
**Pull request by rgbriggs**
Check to verify that execve syscall rules don't generate BPRM_FCAPS auxilliary
records when triggered by a transition from unprivileged user to root.

See: https://github.com/linux-audit/audit-kernel/issues/16

Signed-off-by: Richard Guy Briggs <rgb@redhat.com>

### CODE REVIEW

**Comment by pcmoore** [comment]
Two quick comments/questions:

* A nitpicky comment, but the test subdirectory is pretty awkward, how about exec_bprm_fcaps?  I'm open to other suggestions if you're not in love with that, but the current choice is pretty bad in my opinion.
* Have you attempted making this an automated test?  I'm largely thinking out loud, but it seems like there might be some combination of scripting and /bin/su which could handle the automation.  If you've already tried this and given up in frustration I'd be curious to hear about the pitfalls.

**Comment by rgbriggs** [comment]
On 2018-02-22 15:43, Paul Moore wrote:
> Two quick comments/questions:
> 
> * A nitpicky comment, but the test subdirectory is pretty awkward, how about exec_bprm_fcaps?  I'm open to other suggestions if you're not in love with that, but the current choice is pretty bad in my opinion.

I agree it is awkward.  I'd prefer syscall_execve-bprm_fcaps, but I
could accept exec_bprm_fcaps if you feel strongly about it.

> * Have you attempted making this an automated test?  I'm largely thinking out loud, but it seems like there might be some combination of scripting and /bin/su which could handle the automation.  If you've already tried this and given up in frustration I'd be curious to hear about the pitfalls.

Yes.  The biggest challenge is the name of an unprivileged account on a
random system.  All systems have root, and there are other unprivileged
accounts that are mostly consistently present, but they aren't login
accounts with a shell set.  Thinking about it, it would be possible to
script the addition of a temporary unpriveleged account with a
random-generated name to perform the test and then delete that temporary
account after, which seemed like a lot of work, but then running a test
script manually is a lot more work in the long run.  Would you accept
that solution or do you see a simpler one?

**Comment by pcmoore** [comment]
I'm in the process of cleaning up the PRs and I'm on the fence about this test.  It looks a lot like a bug specific test and not a feature/regression test, which is the focus of this test suite, and when combined with the fact that it is a manual test, I think I'm going to reject this PR and mark it as closed.

We can continue the discussion in this PR if you like (I'm sure you are going to have something to say about this @rgbriggs).

**Comment by rgbriggs** [comment]
On 2018-12-12 09:22, Paul Moore wrote:
> I'm in the process of cleaning up the PRs and I'm on the fence about this test.  It looks a lot like a bug specific test and not a feature/regression test, which is the focus of this test suite, and when combined with the fact that it is a manual test, I think I'm going to reject this PR and mark it as closed.

I was looking for feedback on the suggestions about what direction to go including how to un-manualify it before spending additional time on it.

**Pull request closed without merging**
